/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEbookDownloadRouteImport } from './routes/api/public/ebook-download'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEbookDownloadRoute = ApiPublicEbookDownloadRouteImport.update({
  id: '/api/public/ebook-download',
  path: '/api/public/ebook-download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/ebook-download': typeof ApiPublicEbookDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/ebook-download': typeof ApiPublicEbookDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/api/public/ebook-download': typeof ApiPublicEbookDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thank-you' | '/api/public/ebook-download'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thank-you' | '/api/public/ebook-download'
  id: '__root__' | '/' | '/thank-you' | '/api/public/ebook-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiPublicEbookDownloadRoute: typeof ApiPublicEbookDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ebook-download': {
      id: '/api/public/ebook-download'
      path: '/api/public/ebook-download'
      fullPath: '/api/public/ebook-download'
      preLoaderRoute: typeof ApiPublicEbookDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouRoute: ThankYouRoute,
  ApiPublicEbookDownloadRoute: ApiPublicEbookDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
